#################################################
#################################################
# youtube compose file



version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - ./:/app 
      - /app/node_modules
    # env_file:
    #   - ./.env
    environment:
      - PORT=4000



#################################################
#################################################
# tutorialsPoint compose file

# version: '3'
# services:
#   databases:
#     image: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#       - MYSQL_DATABASE=demodb
#   web:
#    image: nginx
