version: '3'
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=root
      - MONGO_PASWD=example
      - MONGO_IP=mongodb
      - MONGO_PORT=27017
    command: node server.js
    
  mongo:
    ports:
      - '2717:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example