version: '3'
services:
  nginx: 
    ports:
      - '3000:80'
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    # anonymous volume 
    volumes:
      - ./:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASWD=example
      - MONGO_IP=mongodb
      - MONGO_PORT=27017
    command: npm run dev

  mongo:
    ports:
      - '2717:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example