version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    # port 3000 for out localhost and port 80 used because nginx run on port 80 
    ports:
      - '3000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  node-app:
    # container_name: node-api
    build: .
    # if we have to use nginx then ports are define in nginx image and ports are different for all environment
    # ports:
    #   - '4000:4000' # Expose the port for nginx
    environment:
      PORT: 4000 
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    # name volume 
    volumes: 
      - v-mongo-db:/data/db 

# name volume declaration
volumes:
  # v-mongo-db: 
  # or
  v-mongo-db: {}